# Generated by Django 4.2.25 on 2025-10-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the name.', unique=True)),
                ('description', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=5)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order; lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the category from the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
