# Generated by Django 4.2.25 on 2025-10-12 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(help_text='Full sentence solution', max_length=255)),
                ('clue', models.CharField(help_text='Clue to get the player started', max_length=255)),
                ('par_score', models.PositiveIntegerField(default=5)),
                ('daily_puzzle_date', models.DateField(blank=True, help_text='If set, this is the daily puzzle for this date.', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='core.category')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
