# Generated by Django 4.2.25 on 2025-10-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_puzzle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='solution',
            field=models.CharField(help_text='Full sentence solution', max_length=255, unique=True),
        ),
    ]
