# Generated by Django 4.2.25 on 2025-10-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_puzzle_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='daily_puzzle_date',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='position',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
