# Generated by Django 4.2.25 on 2025-10-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_position_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='position',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
