# Generated by Django 4.2.25 on 2025-10-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_puzzle_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='puzzle',
            unique_together={('category', 'position')},
        ),
    ]
