# Generated by Django 4.2.25 on 2025-10-12 16:52

from django.db import migrations


def reset_positions_per_category(apps, schema_editor):
    """Reset position values to start from 1 within each category"""
    Puzzle = apps.get_model('core', 'Puzzle')
    Category = apps.get_model('core', 'Category')

    # Get all categories
    categories = Category.objects.all()

    for category in categories:
        # Get all puzzles for this category, ordered by current position
        puzzles = Puzzle.objects.filter(category=category).order_by('position', 'created_at')

        # Reset positions to start from 1
        for index, puzzle in enumerate(puzzles, start=1):
            puzzle.position = index
            puzzle.save(update_fields=['position'])

        print(f"Reset {puzzles.count()} puzzle positions for category: {category.name}")


def reverse_reset_positions(apps, schema_editor):
    """Reverse migration - restore global unique positions"""
    Puzzle = apps.get_model('core', 'Puzzle')

    # Get all puzzles ordered by category and position
    puzzles = Puzzle.objects.all().order_by('category__id', 'position')

    # Reset to global positions
    for index, puzzle in enumerate(puzzles, start=1):
        puzzle.position = index
        puzzle.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_update_position_per_category'),
    ]

    operations = [
        migrations.RunPython(reset_positions_per_category, reverse_reset_positions),
    ]
