# Generated by Django 4.2.25 on 2025-10-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reset_positions_per_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='clerk_user_id',
            new_name='clerk_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
