# Generated by Django 4.2.25 on 2025-10-12 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('levelup', 'Levels'), ('endless', 'Endless'), ('daily', 'Daily')], help_text='The game mode this progress record is for.', max_length=128)),
                ('score', models.IntegerField(default=0, help_text='For Endless: highest round. For Levels and Daily: guess count')),
                ('attempts_data', models.TextField(blank=True, help_text="Stores the Wordle-style guess string for 'Levels' mode.", null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, help_text='The date and time this record was last updated.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.category')),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('game_mode', 'levelup')), fields=('user', 'puzzle', 'game_mode'), name='uq_one_try_per_user_puzzle_in_levelup'),
        ),
    ]
