# Generated by Django 4.2.25 on 2025-10-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprogress_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'game_mode'], name='core_userpr_user_id_ada230_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['puzzle', 'game_mode'], name='core_userpr_puzzle__bd045d_idx'),
        ),
    ]
