# Generated by Django 4.2.25 on 2025-10-13 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprogress_core_userpr_user_id_ada230_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.category'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EndlessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endless_scores', to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endless_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endless Score',
                'verbose_name_plural': 'Endless Scores',
                'indexes': [models.Index(fields=['category', '-high_score'], name='core_endles_categor_ec3d12_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='endlessscore',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='uq_endless_user_category'),
        ),
    ]
